---
- name: Pull docker image from dockerhub
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull docker image
      docker_image:
        name: swaroop27/speminiproject
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calculator-using-devops
        image: jasvinjames/calculator-using-devops
        state: started
        tty: yes
        interactive: yes