---
- name: Pull docker image from dockerhub
  hosts: all

  tasks:
    - name: Pull docker image
      docker_image:
        name: swaroop27/speminiproject
        source: pull

    - name: start docker container
      docker_container:
        name: swaroop27/speminiproject
        image: swaroop27/speminiproject
        state: started
        try: yes
        interactive: yes
